#!/bin/bash
set -e

run()
{
	echo '$ ' "$@"
	"$@"
}

cp src/draco/tools/draco_encoder.cc "$AUTOPKGTEST_TMP"/test.cpp
cd "$AUTOPKGTEST_TMP"
cat > CMakeLists.txt << EOF
cmake_minimum_required(VERSION 3.18.4)
project(draco_test)
find_package(draco REQUIRED)

add_executable(test_static test.cpp)
target_link_libraries(test_static PRIVATE draco::draco_static)

add_executable(test_shared test.cpp)
target_link_libraries(test_shared PRIVATE draco::draco)
EOF
mkdir build
cd build
run cmake .. -DCMAKE_BUILD_TYPE=Release
run make VERBOSE=ON
run ./test_static -h >/dev/null
run ./test_shared -h >/dev/null
