#!/bin/bash
set -e

cd "$AUTOPKGTEST_TMP"
cat > CMakeLists.txt << EOF
cmake_minimum_required(VERSION 3.18.4)
project(draco_test)
find_package(draco REQUIRED)
find_package(draco REQUIRED)
EOF
mkdir build
cd build
cmake ..

